# Generated by Django 4.2.5 on 2023-10-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_wish_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwish',
            name='your_wish',
        ),
    ]
