# Generated by Django 4.2.5 on 2023-10-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_userwish_your_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwish',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
