# Generated by Django 4.2.5 on 2023-10-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0005_alter_userwish_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='wish',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wish',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserWish',
        ),
    ]
